num1 = input("Введите первое число")
num2 = input("Введите второе число")
num3 = input("Введите третье число")
num1 = float(num1)
num2 = int(num2)
num3 = int(num3)
print(num1 + num2 + num3)
print(15000 - (num1 + num2 + num3))
